site_name: "Ressources SNT / NSI Montesquieu"
site_description: "Cours et ressources"

copyright: |
  © 2026 Paul Tournaille - Ressources SNT / NSI Montesquieu

theme:
  name: material
  language: fr

  icon:
    logo: material/home

  palette:

    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mode sombre

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mode clair

  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:

  - admonition

  - pymdownx.details

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.snippets

  - pymdownx.tabbed:
      alternate_style: true

  - attr_list

  - md_in_html

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:

  - Accueil : index.md

  - SNT :
      - Présentation: snt/index.md
      - Ressources : 
        - Internet: snt/ressources/internet/internet.md
        - Web: snt/ressources/web/web.md
        - Réseaux sociaux: snt/ressources/reseaux_soc/reseaux_soc.md
        - Données structurées: snt/ressources/data/data.md
        - Localisation, cartographie et mobilité : snt/ressources/localisation/localisation.md
        - Informatique embarquée et objets connectés : snt/ressources/embarque/embarque.md
        - Photographie numérique : snt/ressources/photo/photo.md

  

  - Première NSI :
          - Présentation: nsi/premiere/index.md
          - Python: nsi/premiere/python.md
          - Types construits: nsi/premiere/types_construits.md
          - Web: nsi/premiere/web.md
          - Algorithmique: nsi/premiere/algo.md

  - Terminale NSI :
          - Présentation: nsi/terminale/index.md
          - BAC : nsi/terminale/BAC/index.md
          - Projets : nsi/terminale/Projets/index.md
          - Ressources : 
            - Révisions : nsi/terminale/ressources/revisions/revisions.md
            - Histoire de l'informatique : nsi/terminale/histoire.md
            - Structure de données : 
              - Structures linéaires : nsi/terminale/lineaire.md
              - Arbres : nsi/terminale/arbres.md
              - Graphes: nsi/terminale/graphes.md
            - Bases de données : 
              - BDD relationnelle : nsi/terminale/bdd.md
              - Langage SQL : nsi/terminale/sql.md
            - Architectures matérielles, OS et réseaux :
              - Système sur puce : nsi/terminale/embarque.md
              - Processus : nsi/terminale/processus.md
              - Routage : nsi/terminale/routage.md
              - Sécurisation des communications : nsi/terminale/secu.md
            - Langages et programmation :
              - Calculabilité, décidabilité : nsi/terminale/calculabilite.md
              - Récursivité : nsi/terminale/recursivite.md
              - Modularité : nsi/terminale/modularite.md
              - Paradigmes de programmation (POO): nsi/terminale/ressources/paradigmes/paradigmes.md
              - Gestion des bugs : nsi/terminale/bugs.md
            - Algorithmique :
              - Arbres binaires et ABR : nsi/terminale/abr.md
              - Graphes : nsi/terminale/algo_graphes.md
              - Diviser pour régner : nsi/terminale/diviser.md
              - Programmation dynamique : nsi/terminale/prog_dyn.md
              - Recherche textuelle : nsi/terminale/recherche_txt.md
          - Jeux de révision : 
            - Mur NSI : jeux/mur/index.md
            - Conquête NSI : jeux/carte/index.md
            


  - Outils/Liens utiles : outils/index.md

  



  
      
